#!/bin/bash

delim="|"


status() {
    #eval fortune -s
    
    #echo "$delim"
    
    echo "i use arch btw"

    echo "$delim"
    
    #print date and time
    date +"%A %B %u %I:%M %p"
      
}


while true; do
    xsetroot -name "$(status | tr '\n' ' ')"

    #run the loop each minute
    sleep 1m
done
